### PR TITLE
New: Add "quiet" option to omit warning reports (fixes #11)

### LINKED ISSUE #11: Implement quiet as an option
I believe back in v0.0.5, passing the undocumented `quiet: true` in the Grunt configuration actually worked to suppress warning outputs in the command line. The latest version (v1.0.0) isn't passing this option. It would be great if it is implemented to reduce clutter while watching files.

### PR DESCRIPTION
**Pull request by charliecm**
Resolves #11. I'll leave it up to you to include the option in the readme.

### CODE REVIEW

**Comment by gyandeeps** [comment]
Thanks for the Pr.
can you please append your commit message with "(fixes #xxxx)". Thanks

**Comment by gyandeeps** [comment]
To change the commit on the PR, these are the steps:

```sh
git commit --amend
git push --force
```

**Comment by charliecm** [comment]
Done. Thanks for the tip.

**Comment by gyandeeps** [comment]
LGTM :+1:

**Pull request merged**
